In [1]:
import cv2
img = cv2.imread("atmiya.png",0)
#resized_image = cv2.resize(img, (650,500))
cv2.imshow("atmiya",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [2]:
import cv2
face_cascade = cv2.CascadeClassifier("haarcascade_frontalface_default.xml")
img = cv2.imread("sach.jpg")
gray_img = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
faces = face_cascade.detectMultiScale(gray_img, scaleFactor = 1.05,minNeighbors=5)
for x,y,w,h in faces:
    img = cv2.rectangle(img, (x,y), (x+w,y+h),(0,255,0),3)
resized = cv2.resize(img, (500,450)) 
cv2.imshow("Gray", resized)
cv2.waitKey(2000)
cv2.destroyAllWindows()

In [6]:
import cv2 ,time
video = cv2.VideoCapture(0)
check,frame = video.read()
print(check)
cv2.imshow("Capturing",frame)
cv2.waitKey(500)

# print(check)
# print(frame)
# time.sleep(3)
video.release()
cv2.destroyAllWindows

True


<function destroyAllWindows>

In [ ]:
import cv2,time
video = cv2.VideoCapture(0)
a = 1
while True:
    a = a + 1
    check,frame = video.read()
    print(frame)
    gray= cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    cv2.imshow("Capturing",gray)
    key = cv2.waitKey(1)
    if key == ord('q'):
        break
print(a)
video.release()
cv2.destroyAllWindows

In [ ]:
import cv2,time
from datetime import datetime
import pandas

first_frame = None
video = cv2.VideoCapture(0)

while True:
    check,frame = video.read()
    print(frame)
    gray= cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    gray = cv2.GaussianBlur(gray,(21,21),0)
    if first_frame is None:
        first_frame = gray
        continue
delta_frame = cv2.absdiff(first_frame,gray)
thres_delta = cv2.threshold(delta_frame, 30 , 255 , cv2.THRESH_BINART)[1]
thres_delta = cv2.dilate(thres_delta,None,iterations=0)
(_,cnts,_)= cv2.findContours(thresh_delta.copy(),cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIPLE)

for contour in cnts:
    if cv2.contourArea(counter) < 1000:
        continue
    (x,y,w,h)=cv2.boundingRect(contour)
    cv2.rectangle(frame, (x,y), (x+w,y+h),(0,255,0),3)
    
cv2.imshow('frame',frame)
cv2.imshow('Capturing',gray)
cv2.imshow('delta',delta_frame)
cv2.imshow('thresh',thresh_delta)
key = cv2.waitKey(1)
if key == ord('q'):
    break
video.release()
cv2.destroyAllWindows

first_frame = None
status_list=[None,None]
times=[]
df = pandas.DataFrame(columns=["Start","End"])
video = cv2.VideoCapture(0)

while True:
    check,frame = video.read()
    status =0
    gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    gray = cv2.GaussianBlur(gray,(21,21),0)
(_,cnts,_)= cv2.findContours(thresh_delta.copy(),cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIPLE)

for contour in cnts:
    if cv2.contourArea(counter) < 1000:
        continue    
    status=1
    (x,y,w,h)=cv2.boundingRect(contour)
    cv2.rectangle(frame, (x,y), (x+w,y+h),(0,255,0),3)

status_list.append(status)

status_list = status_list[-2:]

if status_list[-1]==1 and status_list[-2:]==0:
    times.append(datetime.now())
if status_list[-1]==0 and status_list[-2:]==1:
    times.append(datetime.now())
    
print(status_list)
print(times)

for i in range(0,len(times),2):
    df=df.append({"start":times[i],"End":times[i+1]},ignore_index=True)
df.to_csv("times.csv")
video.release()
cv2.destroyAllWindows


[[[164 115  75]
  [163 114  74]
  [161 115  66]
  ...
  [219 219 220]
  [218 218 219]
  [214 214 215]]

 [[161 112  70]
  [161 112  70]
  [155 112  65]
  ...
  [218 218 218]
  [211 211 212]
  [206 206 207]]

 [[155 112  65]
  [155 112  65]
  [153 108  66]
  ...
  [211 211 212]
  [207 207 208]
  [207 207 208]]

 ...

 [[144 138 130]
  [144 138 130]
  [146 140 132]
  ...
  [ 19  13  10]
  [ 22  16  13]
  [ 23  17  14]]

 [[143 137 129]
  [145 139 131]
  [146 140 132]
  ...
  [ 25  24  20]
  [ 25  24  20]
  [ 22  21  17]]

 [[144 136 133]
  [146 138 135]
  [144 137 138]
  ...
  [ 28  27  23]
  [ 28  27  23]
  [ 26  25  21]]]
[[[147 118  62]
  [145 116  60]
  [152 112  64]
  ...
  [222 222 223]
  [217 221 221]
  [213 217 217]]

 [[145 116  60]
  [146 117  61]
  [149 115  64]
  ...
  [209 209 210]
  [203 207 208]
  [199 203 204]]

 [[140 110  59]
  [147 117  66]
  [149 119  68]
  ...
  [203 203 204]
  [200 200 201]
  [199 199 200]]

 ...

 [[140 139 135]
  [138 137 133]
  [143 137 134]
  ..

[[[146 111  62]
  [150 115  66]
  [139 113  68]
  ...
  [207 207 207]
  [204 204 205]
  [203 203 204]]

 [[140 110  65]
  [143 113  68]
  [140 110  65]
  ...
  [200 200 200]
  [201 201 202]
  [202 202 203]]

 [[136 106  63]
  [144 114  71]
  [139 113  70]
  ...
  [204 204 204]
  [211 211 211]
  [214 214 214]]

 ...

 [[142 139 129]
  [139 136 126]
  [143 138 128]
  ...
  [ 16   9  10]
  [ 16   9  10]
  [ 17  10  11]]

 [[143 138 128]
  [141 136 126]
  [140 135 125]
  ...
  [ 18  11  12]
  [ 19  12  13]
  [ 21  14  15]]

 [[144 139 129]
  [144 139 129]
  [145 140 130]
  ...
  [ 23  17  14]
  [ 22  15  16]
  [ 22  15  16]]]
[[[147 114  72]
  [146 113  71]
  [154 109  69]
  ...
  [202 202 202]
  [203 203 203]
  [202 202 202]]

 [[152 110  69]
  [152 110  69]
  [150 108  67]
  ...
  [199 199 199]
  [201 201 201]
  [197 197 197]]

 [[132  90  49]
  [143 101  60]
  [147 105  64]
  ...
  [204 204 204]
  [207 207 207]
  [204 204 204]]

 ...

 [[144 138 135]
  [143 137 134]
  [143 137 129]
  ..

[[[155 103  62]
  [155 103  62]
  [156 107  65]
  ...
  [198 209 209]
  [199 210 210]
  [201 212 212]]

 [[153 104  62]
  [153 104  62]
  [151 109  66]
  ...
  [194 203 203]
  [193 202 202]
  [195 204 204]]

 [[143  98  56]
  [154 109  67]
  [153 111  68]
  ...
  [191 200 200]
  [191 200 200]
  [193 202 202]]

 ...

 [[140 139 135]
  [140 139 135]
  [139 138 134]
  ...
  [ 17  13   5]
  [ 19  13  10]
  [ 21  15  12]]

 [[137 136 132]
  [139 138 134]
  [135 134 130]
  ...
  [ 21  20  16]
  [ 25  19  16]
  [ 25  19  16]]

 [[134 133 129]
  [138 137 133]
  [134 132 132]
  ...
  [ 29  23  20]
  [ 25  24  20]
  [ 26  25  21]]]
[[[150 110  43]
  [151 111  44]
  [158 113  53]
  ...
  [209 207 208]
  [208 208 208]
  [206 206 206]]

 [[153 113  46]
  [153 113  46]
  [159 117  56]
  ...
  [202 200 200]
  [202 202 202]
  [206 206 206]]

 [[152 114  53]
  [153 115  54]
  [155 120  58]
  ...
  [201 201 201]
  [201 201 201]
  [203 203 203]]

 ...

 [[133 132 128]
  [134 133 129]
  [132 131 127]
  ..

[[[156 113  54]
  [157 114  55]
  [143 117  60]
  ...
  [207 211 211]
  [201 210 209]
  [202 211 210]]

 [[147 109  54]
  [152 114  59]
  [149 116  60]
  ...
  [203 207 207]
  [202 206 206]
  [205 209 209]]

 [[139 106  50]
  [143 110  54]
  [147 113  62]
  ...
  [200 204 204]
  [202 206 206]
  [204 208 208]]

 ...

 [[138 132 129]
  [139 133 130]
  [139 135 127]
  ...
  [ 15  16  12]
  [ 16  17  13]
  [ 17  18  14]]

 [[138 134 126]
  [139 135 127]
  [138 134 126]
  ...
  [ 16  17  13]
  [ 15  16  12]
  [ 15  16  12]]

 [[136 132 124]
  [138 134 126]
  [136 132 124]
  ...
  [ 21  19  19]
  [ 20  18  18]
  [ 18  16  16]]]
[[[144 114  69]
  [145 115  70]
  [147 114  70]
  ...
  [210 219 218]
  [219 220 216]
  [218 219 215]]

 [[139 113  68]
  [140 114  69]
  [143 113  68]
  ...
  [213 223 218]
  [219 220 216]
  [219 220 216]]

 [[137 111  66]
  [138 112  67]
  [142 109  65]
  ...
  [199 203 203]
  [206 206 206]
  [206 206 206]]

 ...

 [[144 138 135]
  [145 139 136]
  [144 138 135]
  ..

[[[157 115  54]
  [157 115  54]
  [160 115  61]
  ...
  [211 211 211]
  [207 211 211]
  [212 216 216]]

 [[152 113  54]
  [150 111  52]
  [154 116  61]
  ...
  [208 208 208]
  [202 206 206]
  [202 206 206]]

 [[147 109  54]
  [150 112  57]
  [153 115  60]
  ...
  [202 206 206]
  [198 207 206]
  [200 209 208]]

 ...

 [[139 140 131]
  [139 140 131]
  [137 138 129]
  ...
  [ 21  19  19]
  [ 16  16  16]
  [ 15  15  15]]

 [[137 138 129]
  [134 135 126]
  [134 133 129]
  ...
  [ 26  24  24]
  [ 20  18  18]
  [ 17  15  15]]

 [[135 136 127]
  [138 139 130]
  [139 140 131]
  ...
  [ 27  25  25]
  [ 30  23  24]
  [ 29  22  23]]]
[[[137 114  50]
  [135 112  48]
  [137 113  51]
  ...
  [194 203 203]
  [194 203 202]
  [195 204 203]]

 [[130 104  47]
  [133 107  50]
  [138 115  51]
  ...
  [195 204 204]
  [194 203 202]
  [195 204 203]]

 [[126  93  49]
  [138 105  61]
  [143 116  64]
  ...
  [214 218 218]
  [211 220 219]
  [214 223 222]]

 ...

 [[140 134 126]
  [141 135 127]
  [138 132 124]
  ..

[[[161 111  65]
  [162 112  66]
  [157 112  70]
  ...
  [205 203 203]
  [203 203 203]
  [204 204 204]]

 [[160 108  67]
  [163 111  70]
  [155 113  70]
  ...
  [203 203 203]
  [203 203 203]
  [201 201 201]]

 [[156 107  67]
  [160 111  71]
  [155 113  70]
  ...
  [199 199 199]
  [203 203 203]
  [203 203 203]]

 ...

 [[138 137 133]
  [139 138 134]
  [141 137 129]
  ...
  [ 12  15   6]
  [ 12  15   6]
  [ 15  18   9]]

 [[139 138 134]
  [139 138 134]
  [139 133 130]
  ...
  [ 16  19  10]
  [  9  16   7]
  [  8  15   6]]

 [[143 137 134]
  [143 137 134]
  [137 131 128]
  ...
  [ 16  19  10]
  [ 15  18   9]
  [ 13  16   7]]]
[[[146 113  71]
  [147 114  72]
  [154 109  69]
  ...
  [227 220 221]
  [231 222 223]
  [231 222 223]]

 [[145 110  73]
  [147 112  75]
  [152 110  67]
  ...
  [221 212 213]
  [223 214 215]
  [223 214 215]]

 [[149 112  68]
  [153 116  72]
  [150 115  66]
  ...
  [208 199 200]
  [205 198 199]
  [206 199 200]]

 ...

 [[137 133 125]
  [137 133 125]
  [137 138 129]
  ..

[[[148 106  63]
  [151 109  66]
  [153 111  68]
  ...
  [193 204 203]
  [192 203 203]
  [194 205 205]]

 [[143 106  62]
  [146 109  65]
  [145 112  68]
  ...
  [195 199 199]
  [189 200 199]
  [191 202 201]]

 [[131 100  51]
  [142 111  62]
  [142 114  64]
  ...
  [202 211 211]
  [201 210 209]
  [202 211 210]]

 ...

 [[142 135 136]
  [141 134 135]
  [143 137 134]
  ...
  [ 24  17  18]
  [ 19  12  13]
  [ 19  12  13]]

 [[142 135 136]
  [141 134 135]
  [141 134 135]
  ...
  [ 28  21  22]
  [ 25  18  19]
  [ 22  15  16]]

 [[144 137 138]
  [142 135 136]
  [142 135 136]
  ...
  [ 28  21  22]
  [ 28  21  22]
  [ 28  21  22]]]
[[[131 111  58]
  [135 115  62]
  [142 114  64]
  ...
  [208 208 209]
  [206 206 207]
  [206 206 207]]

 [[136 109  57]
  [137 110  58]
  [143 112  63]
  ...
  [203 203 204]
  [203 203 203]
  [200 200 200]]

 [[131 100  51]
  [135 104  55]
  [143 112  63]
  ...
  [202 202 202]
  [196 200 200]
  [198 202 202]]

 ...

 [[137 136 132]
  [139 138 134]
  [138 134 126]
  ..

[[[146 115  54]
  [149 118  57]
  [156 115  61]
  ...
  [194 205 204]
  [195 204 203]
  [194 203 202]]

 [[146 115  54]
  [148 117  56]
  [154 115  65]
  ...
  [193 197 197]
  [188 197 197]
  [189 198 198]]

 [[140 113  61]
  [144 117  65]
  [143 113  62]
  ...
  [204 208 208]
  [205 214 213]
  [206 215 214]]

 ...

 [[143 137 134]
  [142 136 133]
  [144 135 136]
  ...
  [ 13  12   8]
  [ 17  11   8]
  [ 21  15  12]]

 [[144 138 135]
  [144 138 135]
  [143 137 134]
  ...
  [ 18  17  13]
  [ 22  16  13]
  [ 23  17  14]]

 [[144 138 135]
  [144 138 135]
  [144 138 135]
  ...
  [ 24  18  15]
  [ 24  18  15]
  [ 25  19  16]]]
[[[141 117  55]
  [141 117  55]
  [157 114  67]
  ...
  [207 211 211]
  [211 211 211]
  [218 218 218]]

 [[140 114  57]
  [140 114  57]
  [155 113  70]
  ...
  [199 203 203]
  [199 203 203]
  [204 208 208]]

 [[132 108  58]
  [140 116  66]
  [147 110  66]
  ...
  [195 199 199]
  [200 200 200]
  [202 202 202]]

 ...

 [[142 136 133]
  [142 136 133]
  [137 136 132]
  ..

[[[141 113  63]
  [141 113  63]
  [142 112  61]
  ...
  [212 216 216]
  [218 218 218]
  [217 217 217]]

 [[140 113  61]
  [144 117  65]
  [145 114  65]
  ...
  [203 203 203]
  [199 203 203]
  [199 203 203]]

 [[142 115  63]
  [145 118  66]
  [144 113  64]
  ...
  [195 195 195]
  [193 197 197]
  [198 202 202]]

 ...

 [[139 132 133]
  [138 131 132]
  [136 129 130]
  ...
  [ 13  14  10]
  [ 16  17  13]
  [ 16  17  13]]

 [[141 132 133]
  [139 130 131]
  [139 130 131]
  ...
  [ 16  17  13]
  [ 16  17  13]
  [ 13  14  10]]

 [[140 131 132]
  [138 129 130]
  [141 132 133]
  ...
  [ 18  19  15]
  [ 19  20  16]
  [ 17  18  14]]]
[[[143 113  62]
  [146 116  65]
  [145 114  65]
  ...
  [212 216 216]
  [203 212 212]
  [203 212 212]]

 [[144 113  64]
  [146 115  66]
  [148 113  64]
  ...
  [200 209 208]
  [196 205 205]
  [198 207 207]]

 [[151 109  66]
  [154 112  69]
  [153 113  65]
  ...
  [196 205 204]
  [195 204 204]
  [195 204 204]]

 ...

 [[141 135 132]
  [142 136 133]
  [142 135 136]
  ..

[[[165 117  52]
  [164 116  51]
  [160 114  56]
  ...
  [210 210 211]
  [208 208 209]
  [208 208 209]]

 [[158 115  56]
  [158 115  56]
  [160 117  58]
  ...
  [203 203 203]
  [203 203 204]
  [204 204 205]]

 [[152 113  54]
  [157 118  59]
  [159 114  60]
  ...
  [200 200 201]
  [201 201 202]
  [202 202 203]]

 ...

 [[143 135 132]
  [144 136 133]
  [143 135 132]
  ...
  [ 21  20  16]
  [ 15  16   7]
  [ 14  15   6]]

 [[143 134 135]
  [145 136 137]
  [139 133 130]
  ...
  [ 25  21  13]
  [ 21  20  16]
  [ 19  18  14]]

 [[144 136 133]
  [145 137 134]
  [141 134 135]
  ...
  [ 28  24  16]
  [ 28  24  16]
  [ 25  21  13]]]
[[[156 113  66]
  [156 113  66]
  [161 114  67]
  ...
  [215 219 219]
  [214 218 219]
  [212 216 217]]

 [[153 111  62]
  [155 113  64]
  [157 115  66]
  ...
  [204 208 208]
  [207 207 207]
  [203 203 203]]

 [[150 107  60]
  [153 110  63]
  [155 112  65]
  ...
  [192 196 196]
  [199 203 203]
  [198 202 202]]

 ...

 [[144 140 132]
  [143 139 131]
  [145 139 131]
  ..

[[[142 116  59]
  [140 114  57]
  [150 111  52]
  ...
  [217 220 211]
  [206 214 203]
  [206 214 203]]

 [[140 114  57]
  [137 111  54]
  [142 113  57]
  ...
  [202 205 196]
  [199 206 197]
  [203 210 201]]

 [[142 116  59]
  [143 117  60]
  [138 112  55]
  ...
  [195 198 189]
  [197 204 195]
  [199 206 197]]

 ...

 [[143 135 132]
  [144 136 133]
  [145 137 134]
  ...
  [ 30  22  19]
  [ 32  25  26]
  [ 35  28  29]]

 [[145 137 134]
  [146 138 135]
  [144 136 133]
  ...
  [ 29  23  20]
  [ 31  24  25]
  [ 31  24  25]]

 [[145 137 134]
  [146 138 135]
  [143 135 132]
  ...
  [ 30  23  24]
  [ 26  24  25]
  [ 26  24  25]]]
[[[161 112  70]
  [163 114  72]
  [155 113  70]
  ...
  [221 212 213]
  [219 210 211]
  [222 213 214]]

 [[153 111  68]
  [153 111  68]
  [155 110  68]
  ...
  [207 198 199]
  [203 194 195]
  [209 200 201]]

 [[144 107  63]
  [149 112  68]
  [146 113  69]
  ...
  [201 194 195]
  [203 194 195]
  [205 196 197]]

 ...

 [[142 136 133]
  [139 133 130]
  [141 137 129]
  ..

[[[153 111  62]
  [155 113  64]
  [160 113  78]
  ...
  [209 213 213]
  [205 214 213]
  [203 212 211]]

 [[153 104  62]
  [153 104  62]
  [160 111  69]
  ...
  [198 202 202]
  [192 201 200]
  [191 200 199]]

 [[149 104  62]
  [149 104  62]
  [152 107  65]
  ...
  [200 204 204]
  [200 204 204]
  [199 203 203]]

 ...

 [[141 137 122]
  [141 137 122]
  [140 135 125]
  ...
  [ 30  24  21]
  [ 26  24  24]
  [ 28  26  26]]

 [[138 133 123]
  [141 136 126]
  [140 135 125]
  ...
  [ 27  25  25]
  [ 31  24  25]
  [ 31  24  25]]

 [[140 135 125]
  [143 138 128]
  [140 134 126]
  ...
  [ 31  24  25]
  [ 32  23  24]
  [ 34  25  26]]]
[[[150 110  76]
  [151 111  77]
  [149 116  74]
  ...
  [218 218 218]
  [218 219 215]
  [218 219 215]]

 [[148 109  72]
  [151 112  75]
  [151 114  70]
  ...
  [202 206 206]
  [203 203 203]
  [203 203 203]]

 [[142 105  63]
  [146 109  67]
  [154 112  71]
  ...
  [202 202 202]
  [203 203 203]
  [203 203 203]]

 ...

 [[144 138 135]
  [143 137 134]
  [142 136 133]
  ..

[[[152 110  49]
  [156 114  53]
  [157 112  70]
  ...
  [206 206 206]
  [204 204 204]
  [204 204 204]]

 [[152 105  58]
  [153 106  59]
  [159 110  70]
  ...
  [199 199 199]
  [201 201 201]
  [203 203 203]]

 [[147 102  62]
  [155 110  70]
  [154 109  69]
  ...
  [199 199 200]
  [199 199 199]
  [200 200 200]]

 ...

 [[144 140 132]
  [144 140 132]
  [142 138 130]
  ...
  [ 32  28  20]
  [ 33  27  24]
  [ 32  26  23]]

 [[139 140 131]
  [138 139 130]
  [134 135 126]
  ...
  [ 33  27  24]
  [ 31  27  19]
  [ 32  28  20]]

 [[138 139 130]
  [135 136 127]
  [137 138 129]
  ...
  [ 31  25  22]
  [ 31  25  22]
  [ 30  24  21]]]
[[[159 102  64]
  [163 106  68]
  [156 107  67]
  ...
  [206 204 204]
  [208 206 206]
  [208 206 206]]

 [[152 103  63]
  [156 107  67]
  [158 109  69]
  ...
  [202 200 200]
  [199 197 197]
  [199 197 197]]

 [[135  98  54]
  [143 106  62]
  [154 111  64]
  ...
  [210 208 208]
  [205 203 203]
  [203 201 201]]

 ...

 [[133 138 122]
  [136 141 125]
  [135 138 122]
  ..

[[[137 114  70]
  [138 115  71]
  [141 111  68]
  ...
  [209 210 206]
  [205 212 203]
  [204 211 202]]

 [[134 111  67]
  [137 114  70]
  [142 112  69]
  ...
  [204 204 204]
  [199 203 203]
  [199 203 203]]

 [[131 108  64]
  [136 113  69]
  [144 111  69]
  ...
  [199 203 203]
  [206 206 206]
  [206 206 206]]

 ...

 [[144 138 135]
  [144 138 135]
  [142 136 133]
  ...
  [ 24  17  18]
  [ 25  18  19]
  [ 24  17  18]]

 [[142 136 133]
  [144 138 135]
  [141 135 132]
  ...
  [ 31  22  23]
  [ 25  18  19]
  [ 24  17  18]]

 [[139 133 130]
  [144 138 135]
  [143 137 134]
  ...
  [ 31  24  25]
  [ 29  22  23]
  [ 26  19  20]]]
[[[148 106  79]
  [148 106  79]
  [151 114  70]
  ...
  [218 216 217]
  [218 216 216]
  [217 215 215]]

 [[146 106  72]
  [147 107  73]
  [150 115  66]
  ...
  [206 204 205]
  [209 207 208]
  [208 206 207]]

 [[144 107  65]
  [148 111  69]
  [148 111  67]
  ...
  [202 202 203]
  [200 200 201]
  [200 200 201]]

 ...

 [[143 139 131]
  [143 139 131]
  [138 134 126]
  ..

[[[150 105  65]
  [150 105  65]
  [149 110  73]
  ...
  [206 210 210]
  [206 206 206]
  [203 203 203]]

 [[147 103  67]
  [147 103  67]
  [150 108  67]
  ...
  [199 203 203]
  [197 197 197]
  [195 195 195]]

 [[143  99  63]
  [147 103  67]
  [152 108  72]
  ...
  [203 203 203]
  [203 203 203]
  [204 204 204]]

 ...

 [[141 134 135]
  [139 132 133]
  [137 130 131]
  ...
  [ 13  14  10]
  [ 17  15  15]
  [ 22  20  20]]

 [[136 129 130]
  [137 130 131]
  [136 129 130]
  ...
  [ 18  16  16]
  [ 18  16  16]
  [ 20  18  18]]

 [[136 129 130]
  [138 131 132]
  [138 131 132]
  ...
  [ 20  18  18]
  [ 20  18  18]
  [ 21  19  19]]]
[[[151 116  54]
  [152 117  55]
  [151 120  59]
  ...
  [208 211 202]
  [203 208 204]
  [202 207 203]]

 [[151 113  58]
  [152 114  59]
  [153 115  60]
  ...
  [198 202 202]
  [198 202 202]
  [202 206 206]]

 [[142  99  52]
  [154 111  64]
  [149 114  65]
  ...
  [195 204 204]
  [204 208 209]
  [209 213 214]]

 ...

 [[140 141 132]
  [140 141 132]
  [135 136 127]
  ..

[[[138 114  64]
  [139 115  65]
  [154 114  66]
  ...
  [204 204 204]
  [199 203 204]
  [199 203 204]]

 [[143 112  63]
  [147 116  67]
  [150 115  66]
  ...
  [201 201 201]
  [200 198 204]
  [202 200 206]]

 [[132  99  55]
  [142 109  65]
  [150 113  69]
  ...
  [210 210 210]
  [210 210 211]
  [211 211 212]]

 ...

 [[138 132 129]
  [136 130 127]
  [131 130 126]
  ...
  [ 22  16  13]
  [ 19  18  14]
  [ 20  19  15]]

 [[137 131 128]
  [137 131 128]
  [132 131 127]
  ...
  [ 22  20  20]
  [ 21  20  16]
  [ 21  20  16]]

 [[133 132 128]
  [137 136 132]
  [134 133 129]
  ...
  [ 19  18  14]
  [ 20  19  15]
  [ 21  20  16]]]
[[[144 109  60]
  [143 108  59]
  [148 114  63]
  ...
  [211 212 208]
  [210 209 205]
  [206 205 201]]

 [[144 109  60]
  [146 111  62]
  [150 115  66]
  ...
  [203 201 201]
  [201 200 196]
  [201 200 196]]

 [[141 107  56]
  [143 109  58]
  [149 114  65]
  ...
  [197 198 194]
  [195 196 192]
  [195 196 192]]

 ...

 [[134 128 125]
  [136 130 127]
  [136 130 127]
  ..

[[[148 114  63]
  [148 114  63]
  [164 109  64]
  ...
  [211 209 215]
  [208 205 214]
  [214 211 220]]

 [[161 112  64]
  [158 109  61]
  [155 106  58]
  ...
  [203 201 207]
  [200 197 206]
  [200 197 206]]

 [[146 100  51]
  [146 100  51]
  [155 106  58]
  ...
  [202 200 206]
  [203 200 209]
  [206 203 212]]

 ...

 [[134 125 126]
  [137 128 129]
  [136 129 130]
  ...
  [ 12  13   9]
  [ 11  12   8]
  [ 10  11   7]]

 [[135 121 123]
  [136 122 124]
  [135 128 129]
  ...
  [ 13  14  10]
  [ 13  14  10]
  [ 15  16  12]]

 [[134 120 122]
  [135 121 123]
  [137 128 129]
  ...
  [ 18  17  13]
  [ 16  17  13]
  [ 16  17  13]]]
[[[169 105  66]
  [170 106  67]
  [166 107  67]
  ...
  [208 206 206]
  [203 203 203]
  [204 204 204]]

 [[162 103  63]
  [165 106  66]
  [166 107  67]
  ...
  [205 203 203]
  [203 201 207]
  [202 200 206]]

 [[155 103  62]
  [160 108  67]
  [166 109  69]
  ...
  [203 203 203]
  [206 206 206]
  [207 207 207]]

 ...

 [[137 129 126]
  [138 130 127]
  [138 130 127]
  ..

In [ ]:
import cv2,time
from datetime import datetime
import pandas

first_frame = None
status_list=[None,None]
times=[]
df = pandas.DataFrame(columns=["Start","End"])
video = cv2.VideoCapture(0)

while True:
    check,frame = video.read()
    status =0
    gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    gray = cv2.GaussianBlur(gray,(21,21),0)
(_,cnts,_)= cv2.findContours(thresh_delta.copy(),cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIPLE)

for contour in cnts:
    if cv2.contourArea(counter) < 1000:
        continue    
    status=1
    (x,y,w,h)=cv2.boundingRect(contour)
    cv2.rectangle(frame, (x,y), (x+w,y+h),(0,255,0),3)

status_list.append(status)

status_list = status_list[-2:]

if status_list[-1]==1 and status_list[-2:]==0:
    times.append(datetime.now())
if status_list[-1]==0 and status_list[-2:]==1:
    times.append(datetime.now())
    
print(status_list)
print(times)

for i in range(0,len(times),2):
    df=df.append({"start":times[i],"End":times[i+1]},ignore_index=True)
df.to_csv("times.csv")
video.release()
cv2.destroyAllWindows


# save video

In [ ]:
import cv2
import numpy
import matplotlib

cap = cv2.VideoCapture(0)
sav = cv2.VideoWriter_fourcc(*'XVID')
out = cv2.VideoWriter('out.avi' , sav , 20.0 , (640,480))
while True:
    ret , frame = cap.read()
    gray = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    out.write(frame)
    cv2.imshow("frame" , frame)
    cv2.imshow("gray" , gray)
    
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
out.release()
cv2.destroyAllWindows()


# edit image

In [ ]:
import cv2
import numpy
import matplotlib

img = cv2.imread("atmiya.png",1)
cv2.line(img,(0,0),(100,200),(0,0,55),1)
cv2.rectangle(img,(0,0),(50,500),(0,255,0),1)
cv2.circle(img,(100,100),50,(0,255,0),2)
ts = numpy.array([[10,20],[20,30],[30,140],[40,50]],numpy.int32)
cv2.polylines(img , [ts] , True , (255,145,214) , 5)

cv2.imshow("image",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

# add image part

In [ ]:
import cv2
import numpy
import matplotlib

img = cv2.imread("atmiya.png",1)
img1 = cv2.imread("fusion.png",1)

logo = img[10:80 ,15:85]
img1[0:70 , 0:70] = logo
cv2.imshow('image',img1)
cv2.waitKey(0)
cv2.destroyAllWindows()

# add image

In [ ]:
import cv2
import numpy
import matplotlib

img = cv2.imread("atmiya.png",1)
img1 = cv2.imread("fusion.png",1)
im = cv2.resize(img, (177,177))
im1 = cv2.resize(img1, (177,177))
add = im + im1
cv2.imshow('image',add)
cv2.waitKey(0)
cv2.destroyAllWindows()


# threshold

In [ ]:
import cv2
import numpy
import matplotlib

img = cv2.imread("atmiya.png",1)
retval ,thresold = cv2.threshold(img , 200 , 255 ,cv2.THRESH_BINARY)
gray_scal = cv2.cvtColor(img , cv2.COLOR_BGR2GRAY)
retval2 ,thresold2 = cv2.threshold(gray_scal , 200 , 255 ,cv2.THRESH_BINARY)
gues = cv2.adaptiveThreshold(gray_scal,255,cv2.ADAPTIVE_THRESH_GAUSSIAN_C , cv2.THRESH_BINARY , 155 ,1 )

cv2.imshow('image',img)
cv2.imshow('threshold',thresold)
cv2.imshow('gray_scal',gray_scal)
cv2.imshow('gues',gues)
cv2.waitKey(0)
cv2.destroyAllWindows()

# color filtering


In [ ]:
import cv2
import numpy as np
import matplotlib

cap = cv2.VideoCapture(0)
while True:
    _,frame = cap.read()
    hsv = cv2.cvtColor(frame , cv2.COLOR_BGR2HSV)
    
    lower_red = np.array([150,150,50])
    upper_red = np.array([180,255,255])
    
    mask = cv2.inRange(hsv , lower_red , upper_red)
    res = cv2.bitwise_and(frame ,frame , mask=mask)
    
    cv2.imshow("original",frame)
    cv2.imshow("mask",mask)
    cv2.imshow("result",res)
    
    k= cv2.waitKey(5) & 0xFF == ord('q')
    if k == 4:
        break      
cv2.destroyAllWindows()
cap.release()

# edge detection

In [ ]:
import cv2
import numpy as np
import matplotlib

cap = cv2.VideoCapture(0)
while True:
    _,frame = cap.read()
    
    laplacian = cv2.Laplacian(frame , cv2.CV_64F)
    edges = cv2.Canny(frame,100,100)
    
    
    cv2.imshow('original',frame)
    cv2.imshow('laplacian',laplacian)
    cv2.imshow('edges',edges)
        
    
    k= cv2.waitKey(5) & 0xFF == ord('q')
    if k == 4:
        break 
cv2.destroyAllWindows()
cap.release()

# corner detection

In [22]:
import cv2
import numpy as np
import matplotlib

img = cv2.imread("atmiya.png",1)
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
gray = np.float32(gray)

corner = cv2.goodFeaturesToTrack(gray, 500 , 0.01, 1)
corner = np.int0(corner)

for cor in corner:
    x,y = cor.ravel()
    cv2.circle(img,(x,y),3,255,-1)

cv2.imshow("corner",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

# background reduction

In [ ]:
import cv2
import numpy as np
import matplotlib

cap = cv2.VideoCapture(0)
fgbg = cv2.createBackgroundSubtractorMOG2()
while True:
    ret ,frame = cap.read()
    fgmask = fgbg.apply(frame)
    
    cv2.imshow("original",frame)
    cv2.imshow("fgmask",fgmask)
    
    k= cv2.waitKey(30) & 0xFF
    if k == 27:
        break      
cv2.destroyAllWindows()
cap.release()

# face & eye detection

In [ ]:
import numpy as np
import cv2

face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier('haarcascade_eye.xml')
cap = cv2.VideoCapture(0)

while True:
    ret, img = cap.read()
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(gray, 1.2, 5)

    for (x,y,w,h) in faces:
        cv2.rectangle(img,(x,y),(x+w,y+h),(255,0,0),2)
        roi_gray = gray[y:y+h, x:x+w]
        roi_color = img[y:y+h, x:x+w]
        
        eyes = eye_cascade.detectMultiScale(roi_gray)
        for (ex,ey,ew,eh) in eyes:
            cv2.rectangle(roi_color,(ex,ey),(ex+ew,ey+eh),(0,255,0),2)

    cv2.imshow('img',img)
    k = cv2.waitKey(30) & 0xff
    if k == 27:
        break

cap.release()
cv2.destroyAllWindows()

In [5]:
import cv2
import numpy as np

face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

cap = cv2.VideoCapture(0)
while True:
    ret ,frame = cap.read()
    gray = cv2.cvtColor(frame , cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(gray , 1.5 , 5)
    
    for (x,y,w,h) in faces:
        #print(x,y,w,h)
        roi_gray = gray[y:y+h , x:x+w]
        roi_frame = frame[y:y+h , x:x+w]
        img_item = "my img.png"
        cv2.imwrite(img_item , roi_frame)
        cv2.rectangle(frame , (x,y),(x+w,y+h) , (255,0,0) , 3)
    
    cv2.imshow("frame",frame)
    if cv2.waitKey(20) & 0XFF == ord('q'):
        break
cap.release()
cv2.destroyAllWindows()
    
        
    
    
    
    
    

In [15]:
for j in range(1,3):
    if j%2==0:
        print("views-row views-row-"+str(j)+" views-row-even views-row-first")
    else:
        print("views-row views-row-"+str(j)+" views-row-odd views-row-first")
    k = []
    print(type(k))

views-row views-row-1 views-row-odd views-row-first
<class 'list'>
views-row views-row-2 views-row-even views-row-first
<class 'list'>


In [1]:
# from selenium import webdriver
# from bs4 import BeautifulSoup as soup
# from urllib.request import urlopen as uReq
# import pandas as pd

# filename ="orthopedic22.csv"
# f = open(filename,"a")

# headers = "Dr_name , Rate , P_name , Review\n"
# f.write(headers)

# for i in range(1,93):
#     my_url = 'https://www.scoi.com/about-us/patient-reviews?page='+str(i)
#     uClient = uReq(my_url)
#     page_html = uClient.read()
#     uClient.close()
#     page_soup = soup(page_html , "html.parser")
#     rate = []
#     rev = []
#     drname = []
#     pname = []
#     for j in range(1,11):
#         if j%2==0:
#             containers = page_soup.findAll("div",{"class":"views-row views-row-"+str(j)+" views-row-even"})
#         else:
#             containers = page_soup.findAll("div",{"class":"views-row views-row-"+str(j)+" views-row-odd"})
#         container = containers
# #         rate = page_soup.findAll("div",{"class":"views-field views-field-field-doctor-rating"})
# #         #rate.append(arate[0].text)
# #         #a = arate[0].text
# #         drname = page_soup.findAll("div",{"class":"views-field views-field-views-conditional"})
# #         #print(drname[0].text)
# #         pname = page_soup.findAll("div",{"class":"views-field views-field-field-live-review-name review-text"})
# #         #print(pname[0].text)
# #         rev = page_soup.findAll("div",{"class":"views-field views-field-nothing review-text"})
        
#         for container in containers:
#             drname_container = container.findAll("div", {"class": "views-field views-field-views-conditional"})
#             drname = drname_container[0].text.strip()

#             rating_container = container.findAll("div", {"class": "views-field views-field-field-doctor-rating"})
#             rating = rating_container[0].text
            
#             pname_container = container.findAll("div", {"class": "views-field views-field-field-live-review-name review-text"})
#             pname = pname_container[0].text
            
#             rev_container = container.findAll("div", {"class": "views-field views-field-nothing review-text"})
#             rev = rev_container[0].text
            
#             rating = rating.replace("\n","")
#             rating = rating.replace("Patient Rating: ","")
#             drname = drname.replace("Treating Doctor: ","")
#             drname = drname.replace(",",":")
#             pname = pname.replace("–","")
#             rev = rev.replace(",",":")
#             rev = rev.replace("\n"," ")
            
            
            
# #             print(drname)
# #             print(rating)
# #             print(pname)
            
            
#             f.write(drname +  "," +rating + "," + pname +  "\n")
# f.close()
